name: Volta on docker

on:
  workflow_dispatch:

env:
  VOLTA_FEATURE_PNPM: 1

jobs:
  tests:
    defaults:
      run:
        shell: bash
    container:
      image: debian:bullseye-slim
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup volta
        uses: volta-cli/action@v3

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test
